name: flutter_gen_core

description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 2.0.0
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues
authors:
  - Daichi Furiya <dadadada.chop@gmail.com>
  - Mao Yufeng <lcdsmao@gmail.com>

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'

dependencies:
  path: '>=1.8.0-nullsafety <1.9.0'
  yaml: '>=3.0.0-nullsafety.0 <4.0.0'
  mime: '>=1.0.0-nullsafety.0 <2.0.0'
  xml: '>=5.0.0-nullsafety.1 <6.0.0'
  dart_style: '>=1.3.12'
  dartx: ^0.5.0
  color: ^2.1.1
  merge_map: ^1.0.2
  json_annotation: '>=3.1.1'
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: '>=1.16.0-nullsafety <1.17.0'
  effective_dart: ^1.3.0
  build_runner: '>=1.11.2 <1.12.0'
  json_serializable: '>=3.5.1'
